apiVersion: v1
kind: Service
metadata:
  name: kgh
  namespace: default
  labels:
    app: kgh
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8082
    protocol: TCP
    name: http
  selector:
    app: kgh
